appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fXWEtI8TzsmV3HJGSiE7ZV78dBMqG3BoOZm9igwQ3o92J0Q+aaXDRkK3LAArdK5kzr1Q2f+O4fZvCk283QdipkQNlmcXAlqWzgnR87HdXQAYwn3nAe/5U+VRbAgsUuj2O4k+88VhlNIdkMxHtTXYi9S19URyn3cchUZH5OEECKTUfMjKf4sUMiLQVl72dF0riSVYEM9PMD87JQouv6V95UDkvpKr7Arptd0IyvZk0g3SOIHtsi6IHTTSw2rRqDWsb94QhV/ns7N6Xwt9ta6CZ7ArA3sjZs+xuKCg8zGUS8tPIP+1Hl3JPjyHKJX6RPN3qHd1ppKdlGA/qQ90QRxGRq9CFucet2NZkelHgFWeZFnM0rU11Bh2o39pXtvrXxmN3tm/aDi0s2TDmBjDx4h0PzFOvsBbhw+jX/Ei0H55ZgmP+VIXJfGChSAmTbvSXtsAqSOa1e2Z+z/z/li121r7/fy3/q26f0Wbp88TZwEkv2Y7HSsztj2MVR5N8nu93MfOyi0JLuey9uxDqRds2hkZeJDcLybQPRB/OfCoWWKuczno19cbalwalGtAihlYrxR9EsqlyczX9aJpqsQpY+8gQTiZLuXnoVDSt5JqokLvgrtICBge0xcyy6DEqaeMGrjIyDuW/vjOY5+nx6jDcGJEyKIIzbJ53bpZ9j8bcl2qdgg=}
