travis:
  secure:
    BINSTAR_TOKEN: tGGLe15wfyH7Vjhkly/YiRZGAjtri/ckGAIo0AXo4FMGHw/q5oK5DKlSlAPWpb0xWq/nPYTHX3cKefh/AOH416CpxlumxFZEVrUnh8PTYqPwLU/zvoV7SiKQRLqB7WpmIrXkHmopptRJBQaHIiWiLCC7HWK5aIdj3+OmMKTiaggrz+RLhyo20cpSEPhKCE6g/nGw6DXiSlEqVKsLehCn957leMn3wC+M0A0PKtpT9G3c0exM6VkvumwphcxGJSv+PqY4QatgfpIHNYLfNwRFB+DCpipocDDFvxppOTIWTAl7mdH+DumgeJal8aJyOzGVTFwtgYM3pOD/elMDu/1Wyp+7IBgsQHVP4ww8lziqsbNXriXBzfXuknp5BmUy3qGPEe6JboKKbNPD0keeEaH0fvyJH2RBng2TclATurSnj1U7XXTPh0p1hNeqgF91cLa8rMgYt1Q7lB4eNdei53p+K/3B/7+GzxdfQJLSjTHtsAIfa5BpTXJNl2a4cMZKf5lGNvWD4I3TYfDZn1HCMjIf5E0TA26mZuAlkQYN6DsolAHgjEwZYnOzM7E6SJ6e3BqkWQvrO0ABRGxj73f5C69RmZBM0/c0BFtVRn31WkWTwa6s2PAyedt+x2ZLHsjUwEdW1xfEt+sBHIfA0p9sb/T2/UFmy0aV4T1g37Z1JoajY2g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
